FROM paterit/django-postgresql:2.2.7-python3.8.0-alpine3.10

ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-web"
RUN mkdir -p $DIRPATH/{{ project_name }}-web
WORKDIR $DIRPATH/{{ project_name }}-web

COPY . .

