FROM paterit/django-postgresql:2.2.2-python3.7.3-alpine3.9

ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-web"
RUN mkdir -p $DIRPATH/{{ project_name }}-web
WORKDIR $DIRPATH/{{ project_name }}-web

COPY . .

