FROM {{ project_name }}/base:1.0.1
LABEL "application"="{{ project_name }}-testing"
RUN mkdir -p $DIRPATH/{{ project_name }}-testing

RUN wget -q https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/

WORKDIR $DIRPATH/{{ project_name }}-testing
COPY . .
RUN pip install -U pip \
  && pip install -r requirements.txt
