FROM paterit/node-behave-alpine:10.2-behave1.2.5-python3.6.5-alpine3.8


ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-testing"
RUN mkdir -p $DIRPATH/{{ project_name }}-testing

WORKDIR $DIRPATH/{{ project_name }}-testing

COPY . .