FROM paterit/node-behave:15.2-alpine-behave1.2.6-python3


ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-testing"
RUN mkdir -p $DIRPATH/{{ project_name }}-testing

WORKDIR $DIRPATH/{{ project_name }}-testing

COPY . .