FROM paterit/locustio:0.11.0-3.7.2-alpine3.9

RUN apk update && \
        apk add --no-cache \
        curl \
        less \
        make \
        bash


ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-perf"
RUN mkdir -p $DIRPATH/{{ project_name }}-perf
WORKDIR $DIRPATH/{{ project_name }}-perf

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
