FROM nicolargo/glances:latest
LABEL "application"="{{ project_name }}-monitoring-agent"
RUN mkdir -p /etc/glances  
ADD glances.conf /etc/glances
CMD python3 -m glances -C /glances/conf/glances.conf $GLANCES_OPT