FROM nicolargo/glances:v2.11.1
LABEL "application"="{{ project_name }}-monitoring-agent"
RUN mkdir -p /etc/glances  
ADD glances.conf /etc/glances
CMD python -m glances -C /glances/conf/glances.conf $GLANCES_OPT