FROM nginx
LABEL "application"="{{ project_name }}-https"
ENV DIRPATH /opt/{{ project_name }}
RUN mkdir -p $DIRPATH/static \
	&& rm /etc/nginx/conf.d/default.conf
ADD conf.d/ /etc/nginx/conf.d
COPY entry-point.sh .
