FROM nginx:1.17.6-alpine
LABEL "application"="{{ project_name }}-https"

RUN apk update && \
    apk add --no-cache \
        bash

ENV DIRPATH /opt/{{ project_name }}
RUN mkdir -p $DIRPATH/static \
	&& rm /etc/nginx/conf.d/default.conf
ADD conf.d/ /etc/nginx/conf.d
COPY entry-point.sh .
