FROM python:3.6.4-alpine3.7
RUN apk update && \
         apk add \
         curl \
         less \
         vim \
         make \
         bash

ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-base"
