FROM python:3.6.1
RUN apt-get update && \
         apt-get install -y \
         curl \
         less \
         vim

ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-base"

COPY requirements-sum.txt .
RUN pip install -U pip \
	&& pip install -r requirements-sum.txt