FROM python:3.5
RUN apt-get update \
	&& apt-get -y install curl vim less
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g phantomjs-prebuilt