FROM paterit/python-phantomjs
ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-base"
RUN mkdir -p $DIRPATH/{{ project_name }}-web
WORKDIR $DIRPATH/{{ project_name }}-web
COPY requirements.txt .
RUN pip3 install -U pip \
	&& pip3 install -r requirements.txt