FROM paterit/sphinx:2.0.0-python3.7.3-alpine3.9

RUN apk update && \
         apk add \
         make \
         bash

ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-docs"
RUN mkdir -p $DIRPATH/docs
WORKDIR $DIRPATH/docs

COPY . .