FROM paterit/sphinx:1.5.3-python3.6.6-alpine3.8

RUN apk update && \
         apk add \
         make \
         bash

ENV DIRPATH /opt/{{ project_name }}
LABEL "application"="{{ project_name }}-docs"
RUN mkdir -p $DIRPATH/docs
WORKDIR $DIRPATH/docs

COPY . .